site_name: dough

theme:
  name: material

nav:
  - Home: index.md
  - Design:
      - Outputs: design/outputs.md
      - Inputs: design/inputs.md
      - Inputs-Ar: design/inputs_architecture.md
      - Units: design/units.md
      - Testing: design/testing.md
  - Developer guide: developer.md

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
